# Artificial Intelligence Laboratory 2025 CS 4271
## Raksha Pahariya | 2021CSB029

# Connect-4

Connect-4 is a strategic two-player game where participants choose a disc colour and take
turns dropping their coloured discs into a seven-column, six-row grid. Victory is achieved by
forming a line of four discs horizontally, vertically, or diagonally. Several winning strategies
enhance gameplay:


a. Middle Column Placement:
The player initiating the game benefits from placing the first disc in the middle
column. This strategic move maximizes the possibilities for vertical, diagonal, and
horizontal connections, totalling five potential ways to win.


b. Trapping Opponents:
To prevent losses, players strategically block their opponent’s potential winning paths.
For instance, placing a disc adjacent to an opponent’s three-disc line disrupts their
progression and protects the player from falling into traps set by the opponent.


c. "7" Formation:
Employing a "7" trap involves arranging discs to resemble the shape of a 7 on the
board. This strategic move, which can be configured in various orientations, provides
players with multiple directions to achieve a connect-four, adding versatility to their
gameplay.






## Connect-4 Implementation using Minimax Algorithm:
In this scenario, a user engages in a game against the computer, and the Mini-Max
algorithm is employed to generate game states. Mini-Max, a backtracking algorithm
widely used in decision-making and game theory, determines the optimal move for a
player under the assumption that the opponent also plays optimally. Two players, the maximizer and the minimizer, aim to achieve the highest and lowest scores,
respectively. A heuristic function calculates the values associated with each board
state, representing the advantage of one player over the other.

In [ ]:
import numpy as np
import random
import math

ROWS = 6
COLUMNS = 7
PLAYER_PIECE = 1
AI_PIECE = 2
LENGTH = 4

def create_board():
    return np.zeros((ROWS, COLUMNS))

def drop_piece(board, row, col, piece):
    board[row][col] = piece

def is_valid_location(board, col):
    return board[ROWS-1][col] == 0

def get_next_open_row(board, col):
    for r in range(ROWS):
        if board[r][col] == 0:
            return r

def print_board(board):
    print(np.flip(board, 0))

def winning_move(board, piece):
    for c in range(COLUMNS-3):
        for r in range(ROWS):
            if all(board[r][c+i] == piece for i in range(LENGTH)):
                return True

    for c in range(COLUMNS):
        for r in range(ROWS-3):
            if all(board[r+i][c] == piece for i in range(LENGTH)):
                return True

    for c in range(COLUMNS-3):
        for r in range(ROWS-3):
            if all(board[r+i][c+i] == piece for i in range(LENGTH)):
                return True

    for c in range(COLUMNS-3):
        for r in range(3, ROWS):
            if all(board[r-i][c+i] == piece for i in range(LENGTH)):
                return True

    return False

def score_position(board, piece):
    score = 0
    center_array = [int(i) for i in list(board[:, COLUMNS//2])]
    center_count = center_array.count(piece)
    score += center_count * 3
    return score

def is_terminal_node(board):
    return winning_move(board, PLAYER_PIECE) or winning_move(board, AI_PIECE) or len(get_valid_locations(board)) == 0

def minimax(board, depth, maximizingPlayer):
    valid_locations = get_valid_locations(board)
    is_terminal = is_terminal_node(board)
    if depth == 0 or is_terminal:
        if is_terminal:
            if winning_move(board, AI_PIECE):
                return (None, 100000000000000)
            elif winning_move(board, PLAYER_PIECE):
                return (None, -10000000000000)
            else:
                return (None, 0)
        else:
            return (None, score_position(board, AI_PIECE))
    if maximizingPlayer:
        value = -math.inf
        column = random.choice(valid_locations)
        for col in valid_locations:
            row = get_next_open_row(board, col)
            temp_board = board.copy()
            drop_piece(temp_board, row, col, AI_PIECE)
            new_score = minimax(temp_board, depth-1, False)[1]
            if new_score > value:
                value = new_score
                column = col
        return column, value
    else:
        value = math.inf
        column = random.choice(valid_locations)
        for col in valid_locations:
            row = get_next_open_row(board, col)
            temp_board = board.copy()
            drop_piece(temp_board, row, col, PLAYER_PIECE)
            new_score = minimax(temp_board, depth-1, True)[1]
            if new_score < value:
                value = new_score
                column = col
        return column, value

def get_valid_locations(board):
    return [col for col in range(COLUMNS) if is_valid_location(board, col)]

def play_game():
    board = create_board()
    game_over = False
    turn = 0

    while not game_over:
        print_board(board)
        if turn == 0:
            col = int(input("Enter column (0-6): "))
            if is_valid_location(board, col):
                row = get_next_open_row(board, col)
                drop_piece(board, row, col, PLAYER_PIECE)
                if winning_move(board, PLAYER_PIECE):
                    print_board(board)
                    print("Player wins!")
                    game_over = True
        else:
            col, _ = minimax(board, 5, True)
            if is_valid_location(board, col):
                row = get_next_open_row(board, col)
                drop_piece(board, row, col, AI_PIECE)
                if winning_move(board, AI_PIECE):
                    print_board(board)
                    print("AI wins!")
                    game_over = True

        turn = (turn + 1) % 2
        if len(get_valid_locations(board)) == 0:
            print_board(board)
            print("Game over! It's a draw.")
            game_over = True

play_game()

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Enter column (0-6): 1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 2. 0. 0. 0.]]
Enter column (0-6): 3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 2. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [2. 1. 0. 2. 0. 0. 0.]]
Enter column (0-6): 5
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [2. 1. 0. 2. 0. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.

## Connect-4 Implementation using Alpha-Beta Pruning:
To optimize the Mini-Max algorithm, the Alpha-Beta Pruning technique is applied.
Alpha-Beta Pruning involves passing two additional parameters, alpha and beta, to
the Mini-Max function, reducing the number of evaluated nodes in the game tree. By
introducing these parameters, the algorithm searches more efficiently, reaching
greater depths in the game tree. Alpha-Beta Pruning accelerates the search process
by eliminating the need to evaluate unnecessary branches when a superior move has
been identified, resulting in significant computational time savings.

In [ ]:
import numpy as np
import random
import math

ROWS = 6
COLUMNS = 7
PLAYER_PIECE = 1
AI_PIECE = 2
LENGTH = 4

def create_board():
    return np.zeros((ROWS, COLUMNS))

def drop_piece(board, row, col, piece):
    board[row][col] = piece

def is_valid_location(board, col):
    return board[ROWS-1][col] == 0

def get_next_open_row(board, col):
    for r in range(ROWS):
        if board[r][col] == 0:
            return r

def print_board(board):
    print(np.flip(board, 0))

def winning_move(board, piece):
    for c in range(COLUMNS-3):
        for r in range(ROWS):
            if all(board[r][c+i] == piece for i in range(LENGTH)):
                return True

    for c in range(COLUMNS):
        for r in range(ROWS-3):
            if all(board[r+i][c] == piece for i in range(LENGTH)):
                return True

    for c in range(COLUMNS-3):
        for r in range(ROWS-3):
            if all(board[r+i][c+i] == piece for i in range(LENGTH)):
                return True

    for c in range(COLUMNS-3):
        for r in range(3, ROWS):
            if all(board[r-i][c+i] == piece for i in range(LENGTH)):
                return True

    return False

def score_position(board, piece):
    score = 0
    center_array = [int(i) for i in list(board[:, COLUMNS//2])]
    center_count = center_array.count(piece)
    score += center_count * 3
    return score

def is_terminal_node(board):
    return winning_move(board, PLAYER_PIECE) or winning_move(board, AI_PIECE) or len(get_valid_locations(board)) == 0

def minimax(board, depth, alpha, beta, maximizingPlayer):
    valid_locations = get_valid_locations(board)
    is_terminal = is_terminal_node(board)
    if depth == 0 or is_terminal:
        if is_terminal:
            if winning_move(board, AI_PIECE):
                return (None, 100000000000000)
            elif winning_move(board, PLAYER_PIECE):
                return (None, -10000000000000)
            else:
                return (None, 0)
        else:
            return (None, score_position(board, AI_PIECE))
    if maximizingPlayer:
        value = -math.inf
        column = random.choice(valid_locations)
        for col in valid_locations:
            row = get_next_open_row(board, col)
            temp_board = board.copy()
            drop_piece(temp_board, row, col, AI_PIECE)
            new_score = minimax(temp_board, depth-1, alpha, beta, False)[1]
            if new_score > value:
                value = new_score
                column = col
            alpha = max(alpha, value)
            if alpha >= beta:
                break
        return column, value
    else:
        value = math.inf
        column = random.choice(valid_locations)
        for col in valid_locations:
            row = get_next_open_row(board, col)
            temp_board = board.copy()
            drop_piece(temp_board, row, col, PLAYER_PIECE)
            new_score = minimax(temp_board, depth-1, alpha, beta, True)[1]
            if new_score < value:
                value = new_score
                column = col
            beta = min(beta, value)
            if alpha >= beta:
                break
        return column, value

def get_valid_locations(board):
    return [col for col in range(COLUMNS) if is_valid_location(board, col)]

def play_game():
    board = create_board()
    game_over = False
    turn = 0

    while not game_over:
        print_board(board)
        if turn == 0:
            col = int(input("Enter column (0-6): "))
            if is_valid_location(board, col):
                row = get_next_open_row(board, col)
                drop_piece(board, row, col, PLAYER_PIECE)
                if winning_move(board, PLAYER_PIECE):
                    print_board(board)
                    print("Player wins!")
                    game_over = True
        else:
            col, _ = minimax(board, 5, -math.inf, math.inf, True)
            if is_valid_location(board, col):
                row = get_next_open_row(board, col)
                drop_piece(board, row, col, AI_PIECE)
                if winning_move(board, AI_PIECE):
                    print_board(board)
                    print("AI wins!")
                    game_over = True

        turn = (turn + 1) % 2
        if len(get_valid_locations(board)) == 0:
            print_board(board)
            print("Game over! It's a draw.")
            game_over = True

play_game()

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Enter column (0-6): 6
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 1.]]
Enter column (0-6): 6
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 2. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 1.]
 [0. 0. 0. 2. 0. 0. 1.]]
Enter column (0-6): 3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 1.]
 [0. 0. 0. 2. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0.